### ISSUE TITLE
implement不下来

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [smallbuer/JSBridge-Android#1]
implementation 'com.smallbuer:jsbridge:1.0.2'
ERROR: Failed to resolve: jsbridge
Affected Modules: app

**Comment by smallbuer** [comment]
> implementation 'com.smallbuer:jsbridge:1.0.2'
> ERROR: Failed to resolve: jsbridge
> Affected Modules: app

请添加jcenter源 jcenter() { url 'http://jcenter.bintray.com/' } ,可以查看https://mvnrepository.com/artifact/com.smallbuer/jsbridge
