### ISSUE TITLE
关于WebViewJavascriptBridge名称的问题

### ISSUE THREAD

**Issue by wanyt** [smallbuer/JSBridge-Android#12]
iOS使用的bridge名称是WKWebViewJavascriptBridge，想和他们兼容一下，能不能把js串里面的所有WebViewJavascriptBridge都改成WKWebViewJavascriptBridge？然后在html里边调用window.WKWebViewJavascriptBridge

**Comment by smallbuer** [comment]
> iOS使用的bridge名称是WKWebViewJavascriptBridge，想和他们兼容一下，能不能把js串里面的所有WebViewJavascriptBridge都改成WKWebViewJavascriptBridge？然后在html里边调用window.WKWebViewJavascriptBridge

可以的，这么修改的话可以满足，只需要修改BridgeUtil类中的两个JS字符串常亮即可，源JS文件在jscript目录下可参考具体实现

**Comment by wanyt** [comment]
多谢，[Salute][Salute]
