### ISSUE TITLE
bridge方法如果传值string，android端拿到两头会自带双引号

### ISSUE THREAD

**Issue by puzhengwu** [smallbuer/JSBridge-Android#18]
看是否需要调整一下，还是我需要自己去把引号去掉，或者用JSON方式反序列化成String

**Comment by smallbuer** [comment]
> 看是否需要调整一下，还是我需要自己去把引号去掉，或者用JSON方式反序列化成String

由于注入的js代码中有将H5传入的数据进行JSON.stringify(message)处理，可以参考jscript目录下WebViewJavascriptBridge.js中81行，此处对H5传入的数据进行了字符串转换，所以建议H5传入的时候直接以json对象的形式传递即可

**Comment by icetea0822** [comment]
要是前段传的本身就是JSON.stringify咋办，搞死我了，原封不动传过来才对啊

**Comment by smallbuer** [comment]
可以更新到1.0.7版本，已经对H5传入类型进行判断，避免两层引号问题
