### ISSUE TITLE
谢谢，很好用，请问WebViewJavascriptBridge.js还需要吗

### ISSUE THREAD

**Issue by yongyf** [smallbuer/JSBridge-Android#2]
WebViewJavascriptBridge.js这个文件还要加在项目里面吗

**Comment by smallbuer** [comment]
不需要了，已经把JS内容格式化到java类中了

**Comment by smallbuer** [comment]
> WebViewJavascriptBridge.js这个文件还要加在项目里面吗
不需要了，已经把JS内容格式化到java类中了
