### ISSUE TITLE
BridgeWebView 里面 bridgeTiny.freeMemory()这个方法能够给个方法单独暴露出来吗

### ISSUE THREAD

**Issue by skyv95** [smallbuer/JSBridge-Android#21]
我在对单个BridgeWebView对象重复操作的时候,老页面建的桥无法清除

**Comment by smallbuer** [comment]
桥的对象实例化发生APP启动，在Webview创建时进入关联桥，如果只是单纯的进行清理之前注册的桥，可以在业务层通过BridgeTiny对象调用freeMemory()方法；可以参考MainActivity中的BridgeTiny对象
