### ISSUE TITLE
CallBackFunction只能用一次

### ISSUE THREAD

**Issue by icetea0822** [smallbuer/JSBridge-Android#23]
请问js调用Android端代码后的CallBackFunction回调，是只能用一次的吗？返回一次结果之后再调用CallBackFunction就收不到结果了

**Comment by smallbuer** [comment]
> 请问js调用Android端代码后的CallBackFunction回调，是只能用一次的吗？返回一次结果之后再调用CallBackFunction就收不到结果了

桥的调用是一次调用一次回调，调用的时候生成一个自增长的ID作为队列中的回调ID，使用一次就移除销毁了
