### ISSUE TITLE
网页换成网络地址以后无法展示

### ISSUE THREAD

**Issue by DaneilLuo** [smallbuer/JSBridge-Android#7]
我把网页地址换成一个网络地址（eg:https://blog.csdn.net/sk719887916/article/details/47189607），他就没法展示网页

**Comment by DaneilLuo** [comment]
我弄错的，可以使用的，就是比较慢点

**Comment by smallbuer** [comment]
> 我弄错的，可以使用的，就是比较慢点

OK，没问题就好
